### ISSUE TITLE
TypeScript error "Cannot find name 'GridUngroupCommand'"

### ISSUE THREAD

**Issue by bwinklesky** [telerik/kendo-ui-core#8409]
I'm trying to upgrade to version 2025.4.1111, but getting the following error message when trying to build a .NET core project.  

TS2552	(TS) Cannot find name 'GridUngroupCommand'. Did you mean 'GridGroupCommand'?		C:\Repos\calcite\node_modules\kendo-ui-core\index.d.ts	7374	

It appears the GridUngroupCommand interface is missing.  

<img width="1786" height="834" alt="Image" src="https://github.com/user-attachments/assets/e5df2f6d-e68f-436c-a842-9045e4b6ccfc" />

Steps to reproduce:

1. npm install
2. dotnet build

It works fine with 2025.3.825.  

Verion 2025.3.1002 throws this error: 

(TS) Cannot find name 'ShapeConnector'.

<img width="1587" height="1020" alt="Image" src="https://github.com/user-attachments/assets/ea8c4a02-a5b9-4c24-862c-6f8863fb1256" />

Minimal Repo

https://github.com/bwinklesky/kendo

**Comment by Dimitar-Goshev** [comment]
@bwinklesky Thank you for this report. The issue about GridUngroupCommand is fixed with [this commit](https://github.com/telerik/kendo-ui-core/commit/9acf78d406b5249ab237d98027bf1ca6731c6d46) and it will be included in our latest release later this week.
And the ShapeConnector issue was [fixed](https://github.com/telerik/kendo-ui-core/commit/a290723a96112da7e78eaa59487445d75278e949#diff-23525f79370842c0a89cd88affb7bbda424fb8a7279ea4d138356e7c7e47e341R25303) with 2025.4.1111 .
